---
- hosts: VM
  gather_facts: no
  remote_user: ubuntu
  become: yes
  tasks:
    - name: get filename
      shell: "(cd {{ remote_path }} ;/usr/bin/find . -maxdepth 1 -type f) | cut -d'/' -f2"
      register: files_to_fetch
    - name: fetch data files
      fetch:
        src: "{{ remote_path }}{{ item }}"
        dest: "{{ data_path }}"
      with_items: "{{ files_to_fetch.stdout_lines }}"
