---
- hosts: VM
  gather_facts: no
  remote_user: ubuntu
  become: yes
  tasks:
    - name: wait until benchmark finished
      shell: "grep succeeded {{ remote_path }}../state"
      register: grep_succeeded
      retries: 15
      delay: 30
      until: grep_succeeded.rc == 0

    - name: get filename
      shell: "(cd {{ remote_path }} ;/usr/bin/find . -maxdepth 1 -type f) | cut -d'/' -f2"
      register: files_to_fetch

    - name: fetch data files
      fetch:
        src: "{{ remote_path }}{{ item }}"
        dest: "{{ data_path }}"
      with_items: "{{ files_to_fetch.stdout_lines }}"
    - name: get fetched filename
      shell: "cp {{ data_path }}*{{ remote_path }}* {{ data_path }}"
      delegate_to: localhost
      run_once: True